// Generated by CoffeeScript 1.7.1
(function() {
  var prepare;

  prepare = function($) {
    var test_func;
    $.api("/test/:id", "data", $.args());
    test_func = function(code, params) {
      if (code === $.req.app.api.STATUS_OK) {
        return $.params("simple", params.data.text + ". GOT IT!");
      } else {
        return $.params("simple_error", "Something wrong");
      }
    };
    return $.api("simple", test_func);
  };

  module.exports = prepare;

}).call(this);
