// Generated by CoffeeScript 1.7.1
(function() {
  var prepare;

  prepare = function($) {
    return $.api("/test/echo/1", "get", $.args(), $.params());
  };

  module.exports = prepare;

}).call(this);
