// Generated by CoffeeScript 1.7.1
(function() {
  var prepare;

  prepare = function($) {
    $.params("device_info", $.device_info());
    return $.params("query_info", $.query_info());
  };

  module.exports = prepare;

}).call(this);
