// Generated by CoffeeScript 1.7.1
(function() {
  var md5, prepare;

  md5 = require("MD5");

  prepare = function($) {
    var device_hash;
    device_hash = $.query_info("ip") + " " + md5($.query_info("agent"));
    console.log($.cache(device_hash));
    if ($.cache(device_hash) !== void 0) {
      device_hash += "/!\\";
    } else {
      $.cache(device_hash, "here", 10);
    }
    $.params("device_hash", device_hash);
    $.params("device_info", $.device_info());
    return $.params("query_info", $.query_info());
  };

  module.exports = prepare;

}).call(this);
