// Generated by CoffeeScript 1.7.1
(function() {
  var fs, path, yaml;

  path = require('path');

  fs = require("fs");

  yaml = require("js-yaml");

  this.path = path.dirname(process.mainModule.filename);

  this.debug = true;

  this.heartbeat = 100000;

  this.server = yaml.safeLoad(fs.readFileSync(path.join(this.path, '..', 'configs', 'node_service.yaml'), 'utf8'));

  this.app_port = this.server['rest_ws_serv']['port'];

  this.app_host = this.server['rest_ws_serv']['host'];

  this.backend_host = this.server['rest_ws_serv']['backend']['host'];

  this.backend_port = this.server['rest_ws_serv']['backend']['port'];

}).call(this);
