// Generated by CoffeeScript 1.7.1
(function() {
  var Api, Client, app, fs, make_ipc_pack,
    __hasProp = {}.hasOwnProperty;

  make_ipc_pack = function(method, method_type, params) {
    var ipc_pack;
    ipc_pack = {
      api_method: method,
      api_type: method_type,
      token: params.token,
      x_token: params.x_token,
      query_params: params
    };
    return ipc_pack;
  };

  fs = require('fs');

  Client = require('zerorpc').Client;

  app = global.app;

  Api = (function() {
    function Api(app) {
      this.app = app;
      this.STATUS_OK = 200;
      this.STATUS_NOT_FOUND = 404;
      this.STATUS_INTERNAl_ERROR = 500;
      this.client = new Client();
    }

    Api.prototype.call = function(method, method_type, args, params, callback) {
      var ipc_pack, key, val;
      if (args !== void 0) {
        for (key in args) {
          if (!__hasProp.call(args, key)) continue;
          val = args[key];
          method = method.replace(":" + key, val);
        }
      }
      ipc_pack = make_ipc_pack(method, method_type, params);
      this.client.connect(app.config.connection_string);
      return this.client.invoke('route', ipc_pack, function(err, res, more) {
        var e;
        if (err) {
          return callback(500);
        } else {
          try {
            return callback(200, res);
          } catch (_error) {
            e = _error;
            return callback(500);
          }
        }
      });
    };

    return Api;

  })();

  module.exports = Api;

}).call(this);
