// Generated by CoffeeScript 1.8.0
(function() {
  var Api, app, fs,
    __hasProp = {}.hasOwnProperty;

  fs = require('fs');

  app = global.app;

  Api = (function() {
    function Api(app) {
      this.app = app;
      this.STATUS_OK = 200;
      this.STATUS_NOT_FOUND = 404;
      this.STATUS_INTERNAl_ERROR = 500;
    }

    Api.prototype.call = function(method, method_type, args, params, callback) {
      var key, val;
      if (args !== void 0) {
        for (key in args) {
          if (!__hasProp.call(args, key)) continue;
          val = args[key];
          method = method.replace(":" + key, val);
        }
      }
      if (method[0] !== "/") {
        method = "/" + method;
      }
      console.log(this.app.conf.path + '/../tmp/api/v1' + method);
      return fs.readFile(this.app.conf.path + '/../tmp/api/v1' + method, 'utf8', function(err, data) {
        var e, json;
        if (err) {
          return callback(500);
        } else {
          try {
            json = JSON.parse(data.toString());
            return callback(200, json);
          } catch (_error) {
            e = _error;
            return callback(500);
          }
        }
      });
    };

    return Api;

  })();

  module.exports = Api;

}).call(this);

//# sourceMappingURL=api_fake.js.map
