// Generated by CoffeeScript 1.7.1
(function() {
  var fs, path, yaml;

  path = require("path");

  fs = require('fs');

  yaml = require('js-yaml');

  this.path = path.dirname(process.mainModule.filename);

  this.themes_path = this.path + "/themes/";

  this.engine_path = this.path + "/engine/";

  this.lib_path = this.engine_path + "lib/";

  this.jade_path = this.engine_path + "jade/";

  this.helpers_path = this.engine_path + "helpers/";

  this.tpl_page_prefix = "page_";

  this.jade_ext = ".jade";

  this.tpl_config_ext = ".config";

  this.theme_name = "vcms-test";

  this.theme_path = this.themes_path + this.theme_name + "/";

  this.theme_global_config = this.theme_path + ".config";

  this.dict_os = {
    mobile: ["ios", "android", "windows phone"]
  };

  this.dict_devices = {
    tablets: ["ipad", "nexus 10", "nexus 7", "kindle fire", "blackberry playbook"],
    smartphones: ["iphone"],
    smarttv: []
  };

  this.static_url = "static/";

  this.themes_url = this.static_url + "themes/";

  this.theme_url = this.themes_url + this.theme_name + "/";

  this.resources = {
    theme: this.theme_url,
    img: this.theme_url + "img/",
    js: this.theme_url + "js/",
    css: this.theme_url + "css/",
    global: {
      "static": this.static_url,
      img: this.static_url + "img/",
      js: this.static_url + "js/",
      css: this.static_url + "css/"
    }
  };

  this.server = yaml.safeLoad(fs.readFileSync(path.join(this.path, '..', 'configs', 'node_service.yaml'), 'utf8'));

  this.app_port = this.server['render_serv']['port'];

  this.app_host = this.server['render_serv']['host'];

  this.backend_host = this.server['render_serv']['backend']['host'];

  this.backend_port = this.server['render_serv']['backend']['port'];

}).call(this);
