// Generated by CoffeeScript 1.8.0
(function() {
  var fs, path, yaml;

  path = require("path");

  fs = require('fs');

  yaml = require('js-yaml');

  this.path = path.dirname(process.mainModule.filename);

  this.themes_path = this.path + "/themes/";

  this.engine_path = this.path + "/engine/";

  this.lib_path = this.engine_path + "lib/";

  this.jade_path = this.engine_path + "jade/";

  this.helpers_path = this.engine_path + "helpers/";

  this.tpl_page_prefix = "page_";

  this.jade_ext = ".jade";

  this.tpl_config_ext = ".config";

  this.theme_name = "show_online_full";

  this.theme_path = this.themes_path + this.theme_name + "/";

  this.theme_global_config = this.theme_path + ".config";

  this.dict_os = {
    mobile: ["ios", "android", "windows phone"]
  };

  this.dict_devices = {
    tablets: ["ipad", "nexus 10", "nexus 7", "kindle fire", "blackberry playbook"],
    smartphones: ["iphone"],
    smarttv: []
  };

  this.content_url = "http://localhost:63342/vmcs_from_live/tmp/content/";

  this.static_url = "http://localhost:63342/vmcs_from_live/tmp/static/";

  this.cdn_url = "http://localhost:63342/vmcs_from_live/tmp/cdn/";

  this.themes_url = this.static_url + "themes/";

  this.theme_url = this.themes_url + this.theme_name + "/";

  this.resources = {
    theme: this.theme_url,
    img: this.theme_url + "img/",
    js: this.theme_url + "js/",
    css: this.theme_url + "css/",
    global: {
      content: this.content_url,
      content_media: this.content_url + "media/",
      content_users: this.content_url + "users/",
      cdn: this.cdn_url,
      "static": this.static_url,
      img: this.static_url + "img/",
      js: this.static_url + "js/",
      css: this.static_url + "css/"
    }
  };


  /*
  @server = yaml.safeLoad(fs.readFileSync path.join(@path, '..', 'configs', 'node_service.yaml'), 'utf8')
  
   * set app port and host
  @app_port = @server['render_serv']['port']
  @app_host = @server['render_serv']['host']
  
   * set backend(zeroprpc) port and host
  @backend_host = @server['render_serv']['backend']['host']
  @backend_port = @server['render_serv']['backend']['port']
   */

  this.connection_string = 'tcp://' + this.backend_host + ':' + this.backend_port;

  this.backend_host = "127.0.0.1";

  this.backend_port = 6600;

  this.app_host = "127.0.0.1";

  this.app_port = 9901;

}).call(this);

//# sourceMappingURL=config.js.map
