// Generated by CoffeeScript 1.7.1
(function() {
  var prepare, topic_success, tpl;

  tpl = void 0;

  topic_success = function(code, params) {
    var more_topic, topic;
    if (code === tpl.req.app.api.STATUS_OK) {
      topic = params.data;
      tpl.api_get("media/list", "media_pop", {}, {
        limit: 12,
        topic: topic.name,
        sort: "views"
      });
      tpl.api_get("media/list", "media_new", {}, {
        limit: 12,
        topic: topic.name,
        sort: "date"
      });
      tpl.api_get("news/list", "news", {}, {
        limit: 10,
        obj_type: "topic",
        obj_name: topic.name
      });
      topic.country = "Россия";
      if (topic.name === "fizruk") {
        topic.genre = "Сериал";
      } else {
        topic.genre = "Шоу";
      }
      topic.pg_rating = "16+";
      topic.votes_cnt = 10500;
      topic.rating = 8;
      tpl.params("topic", topic);
      if (topic.name === "fizruk") {
        more_topic = {
          title: "Дом 2",
          name: "dom2"
        };
      } else {
        more_topic = {
          title: "Физрук",
          name: "fizruk"
        };
      }
      return tpl.params("more_topic", more_topic);
    } else {
      return tpl.set_fail(404);
    }
  };

  prepare = function($) {
    var url;
    tpl = $;
    url = $.req.query_info("url").substr(1);
    if (url !== "fizruk" && url !== "dom2") {
      return $.set_fail(404);
    } else {
      return $.api_get("topics/:topic/info", topic_success, {
        topic: url
      });
    }
  };

  module.exports = prepare;

}).call(this);
