// Generated by CoffeeScript 1.8.0
(function() {
  var media_success, prepare, tpl;

  tpl = void 0;

  media_success = function(code, params) {
    var media, topic, topic_name, u, unit, _i, _len, _ref;
    if (code === tpl.req.app.api.STATUS_OK) {
      topic_name = tpl.args("topic");
      topic = void 0;
      unit = void 0;
      media = params.data;
      if (media.units && media.units.length) {
        if (topic_name === void 0) {
          unit = media.units[0];
        } else {
          _ref = media.units;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            u = _ref[_i];
            if (u.topic && u.topic && u.topic.name === topic_name) {
              unit = u;
            }
          }
        }
      }
      if (unit) {
        topic = unit.topic;
        topic_name = unit.topic.name;
        tpl.params("media", params.data);
        tpl.params("unit", unit);
        tpl.params("topic", topic);
        return tpl.api_get("news/list", "news", {
          limit: 5
        });
      } else {
        return tpl.set_fail(404);
      }
    } else {
      return tpl.set_fail(404);
    }
  };

  prepare = function($) {
    var args;
    tpl = $;
    args = $.args();
    if (args.id === void 0 || !/d+/.test(args.id.test)) {
      return $.set_fail(404);
    } else {
      return $.api_get("media/:id/info", media_success, {
        id: args.id
      }, {});
    }
  };

  module.exports = prepare;

}).call(this);

//# sourceMappingURL=video.config.js.map
